version: "3.7"

volumes:
  web_data:
    external: true

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.advanced
    volumes:
      - "web_data:/usr/src/app/data"
    environment:
      - APP_PORT=4567
    init: true

  frontend:
    build: ./frontend
    environment:
      - API_URL=http://backend:4567
    ports:
      - "5000:3000"
