version: "3.0"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.advanced
    volumes:
      - "./backend/data.json:/usr/src/app/data.json"
    environment:
      - APP_PORT=4567
    ports:
      - "4567:4567"

  frontend:
    build: ./frontend
    ports:
      - "5000:80"
