version: "3.0"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.advanced
    volumes:
      - "./backend/data:/usr/src/app/data"
    environment:
      - APP_PORT=4567

  frontend:
    build: ./frontend
    environment:
      - API_URL=http://backend:4567
    ports:
      - "5000:3000"
